language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

services:
  - redis-server

install:
  - pip install black==21.4b2
  - pip install pytest==5.4.3
  - pip install pytest-cov codecov
  - pip install redis pyyaml

script:
  - black --check .
  - pytest --cov=./

after_success:
  - codecov

deploy:
  provider: pypi
  edge: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
